version: "3"
services:
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: lab-metasploitable2
    tty: true
    ports:
      - 8180:8180
  bwapp:
    image: raesene/bwapp
    container_name: lab-bwapp
    tty: true
    ports:
      - 8080:80
  badstore:
    image: jvhoof/badstore-docker
    container_name: lab-badstore
    tty: true
    ports:
      - 8090:80
  dvwa:
    image: vulnerables/web-dvwa
    container_name: lab-dvwa
    tty: true
    ports:
      - 8100:80
  juiceshop:
    image: bkimminich/juice-shop
    container_name: lab-juice-shop
    tty: true
    ports:
      - 8110:3000
  kali:
    container_name: lab-kali
    build: .
    tty: true
    ports:
      - 5555:5555
      - 4444:4444
    volumes:
      - ./kali/work:/root
  nginx:
    image: nginx:latest
    container_name: lab-nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/work:/usr/share/nginx/html
