Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.56.200"
  config.vm.network "forwarded_port", guest: 80, host: 8080   # HTTP
  config.vm.network "forwarded_port", guest: 443, host: 4433  # HTTPS
  config.vm.network "forwarded_port", guest: 5900, host: 5900  # VNC
  config.vm.network "forwarded_port", guest: 3000, host: 3000  # rails
  config.vm.network "forwarded_port", guest: 8080, host: 8080  # nuxt
config.vm.box_check_update = false
  config.vm.synced_folder "./work", "/home/vagrant/work",
    :mount_options => ['dmode=775', 'fmode=775']
  config.vm.provision :docker, run: 'always'
  config.vm.provision :docker_compose
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
end
