Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.56.190"
  config.vm.network "forwarded_port", guest: 8834, host: 8834 # Nessus
  config.vm.box_check_update = false
  config.vm.synced_folder "./work","/home/vagrant/work",
    :mount_options => ['dmode=777', 'fmode=777']
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
end
